Repository emelysalmeron/to-do-list-group5, pull requests merged in 2021-08, with the labels that each got.

#3 my schedule
  planning/communication-plan.md
Labels: documentation

#4 adding Moamin's timing to the plan
  planning/communication-plan.md
Labels: documentation

#6 editing the backlog file
  planning/backlog.md
Labels: documentation

#11 add my free hours
  planning/communication-plan.md
Labels: documentation

#26 wireframe link update
  planning/wireframe.md
Labels: documentation

#28 creating the app interface
  client/public/todo list.png
  index.html
Labels: HTML

#33 check mark and delete button
  client/src/handlers/add-to-do.js
  client/src/handlers/handler.js
  client/src/init/index.js
  client/src/listeners/add-to-do-listener.js
  docs/README.md
  docs/dependency-graph.html
  docs/dependency-graph.svg
Labels: handler, javascript

#34 adding CSS to the checklist buttons
  client/styles/other-file.css
Labels: CSS

#40 updated backlog
  planning/backlog.md
Labels: documentation

#42 code refactoring
  client/src/handlers/README.md
  client/src/handlers/add-to-do.js
  client/src/handlers/check-task.js
  client/src/handlers/delete-task.js
  client/src/init/README.md
  client/src/init/index.js
  client/src/listeners/README.md
  client/src/listeners/add-delete-check-listener.js
  client/src/listeners/add-to-do.js
  client/src/listeners/check-task.js
  client/src/listeners/delete-task.js
  docs/README.md
  docs/dependency-graph.html
  docs/dependency-graph.svg
  index.html
  package-lock.json
Labels: listener, handler
